### ISSUE TITLE
Double urls

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/vigour-url#2]
we need to be able to support double urls e.g. discover and a modal or a show and a email token
also check with @ricksmitvigour

**Comment by marcusbesjes** [comment]
It now supports query parameters in "normal" format e.g. `?hurp=shurp` will trigger your listener for `hurp`, and you will have easy access to other parameters in case of `?hurp=shurp&otherparam=othervalue` (when listener for hurp triggers you can check `otherparam`).
